/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChapterIdRouteImport } from './routes/$chapterId'
import { Route as SuiviRouteImport } from './routes/suivi'
import { Route as SuiviIndexRouteImport } from './routes/suivi.index'
import { Route as SuiviJalonsRouteImport } from './routes/suivi.jalons'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapterIdRoute = ChapterIdRouteImport.update({
  id: '/$chapterId',
  path: '/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviRoute = SuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviIndexRoute = SuiviIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuiviRoute,
} as any)
const SuiviJalonsRoute = SuiviJalonsRouteImport.update({
  id: '/jalons',
  path: '/jalons',
  getParentRoute: () => SuiviRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$chapterId': typeof ChapterIdRoute
  '/suivi': typeof SuiviRouteWithChildren
  '/suivi/jalons': typeof SuiviJalonsRoute
  '/suivi/': typeof SuiviIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$chapterId': typeof ChapterIdRoute
  '/suivi/jalons': typeof SuiviJalonsRoute
  '/suivi': typeof SuiviIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$chapterId': typeof ChapterIdRoute
  '/suivi': typeof SuiviRouteWithChildren
  '/suivi/jalons': typeof SuiviJalonsRoute
  '/suivi/': typeof SuiviIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$chapterId' | '/suivi' | '/suivi/jalons' | '/suivi/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$chapterId' | '/suivi/jalons' | '/suivi'
  id: '__root__' | '/' | '/$chapterId' | '/suivi' | '/suivi/jalons' | '/suivi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChapterIdRoute: typeof ChapterIdRoute
  SuiviRoute: typeof SuiviRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$chapterId': {
      id: '/$chapterId'
      path: '/$chapterId'
      fullPath: '/$chapterId'
      preLoaderRoute: typeof ChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi': {
      id: '/suivi'
      path: '/suivi'
      fullPath: '/suivi'
      preLoaderRoute: typeof SuiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi/': {
      id: '/suivi/'
      path: '/'
      fullPath: '/suivi/'
      preLoaderRoute: typeof SuiviIndexRouteImport
      parentRoute: typeof SuiviRoute
    }
    '/suivi/jalons': {
      id: '/suivi/jalons'
      path: '/jalons'
      fullPath: '/suivi/jalons'
      preLoaderRoute: typeof SuiviJalonsRouteImport
      parentRoute: typeof SuiviRoute
    }
  }
}

interface SuiviRouteChildren {
  SuiviJalonsRoute: typeof SuiviJalonsRoute
  SuiviIndexRoute: typeof SuiviIndexRoute
}

const SuiviRouteChildren: SuiviRouteChildren = {
  SuiviJalonsRoute: SuiviJalonsRoute,
  SuiviIndexRoute: SuiviIndexRoute,
}

const SuiviRouteWithChildren = SuiviRoute._addFileChildren(SuiviRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChapterIdRoute: ChapterIdRoute,
  SuiviRoute: SuiviRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
